import assert from "node:assert/strict";
import test from "node:test";
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { formatNoticeLatency, installTps } from "../../src/extensions/tps.mjs";
import { PROCESS_STARTED_AT as SHARED_PROCESS_STARTED_AT, processStartedAt } from "../../src/process-start.mjs";
import {
  agentExtensionShim,
  ensureAgentExtensions,
  OWNED_AGENT_EXTENSIONS,
  RUBATO_EXTENSION_BANNER,
} from "../../src/agent-extensions.mjs";

const PROCESS_STARTED_AT = 42;

function runTurn(assistantMessages, { hasUI = true } = {}) {
  const handlers = new Map();
  const pi = { on: (name, fn) => handlers.set(name, fn) };
  const notices = [];
  const ctx = { hasUI, ui: { notify: (text, level) => notices.push({ text, level }) } };

  installTps(pi, { processStartedAt: PROCESS_STARTED_AT });
  handlers.get("agent_start")({}, ctx);
  for (const message of assistantMessages) {
    handlers.get("message_start")({ message }, ctx);
    // 실제 스트림 대신 message_end 사이에 실제로 시간이 흐른 것처럼 만든다.
    const until = performance.now() + 2;
    while (performance.now() < until) { /* busy wait: 단조 시계가 앞으로 가야 알림이 나온다 */ }
    handlers.get("message_end")({ message }, ctx);
  }
  handlers.get("agent_end")({ messages: assistantMessages }, ctx);
  return notices;
}

function assistant(usage, timing) {
  return { role: "assistant", usage, ...(timing ? { timing } : {}) };
}

const USAGE = { input: 20, output: 100, cacheRead: 80, cacheWrite: 0 };

test("the notice carries delay and think when the turn thought", () => {
  const [notice] = runTurn([
    assistant(USAGE, { processStartedAt: PROCESS_STARTED_AT, ttftMs: 1_000, waitMs: 1_000, thinkMs: 6_000 }),
    assistant(USAGE, { processStartedAt: PROCESS_STARTED_AT, ttftMs: 2_000, waitMs: 2_000, thinkMs: 2_000 }),
    assistant(USAGE, { processStartedAt: PROCESS_STARTED_AT, ttftMs: 600, waitMs: 600 }),
  ]);
  assert.equal(notice.level, "info");
  assert.match(notice.text, /^TPS \d+\.\d tok\/s\. Cache hit \d+\.\d%, \d+\.\ds, delay 1\.2s, think 4\.0s$/);
});

test("a turn without thinking renders delay and no think part", () => {
  const [notice] = runTurn([
    assistant(USAGE, { processStartedAt: PROCESS_STARTED_AT, ttftMs: 400, waitMs: 400 }),
  ]);
  assert.match(notice.text, /, delay 400ms$/);
  assert.doesNotMatch(notice.text, /think/);
});

test("timing from another process is ignored, leaving the original three figures", () => {
  const [notice] = runTurn([
    assistant(USAGE, { processStartedAt: PROCESS_STARTED_AT - 1, ttftMs: 900, waitMs: 900, thinkMs: 5_000 }),
  ]);
  assert.match(notice.text, /^TPS \d+\.\d tok\/s\. Cache hit \d+\.\d%, \d+\.\ds$/);
});

test("the cache-hit and tps figures still come from the summed turn usage", () => {
  const [notice] = runTurn([
    assistant({ input: 20, output: 50, cacheRead: 80, cacheWrite: 0 }),
    assistant({ input: 0, output: 50, cacheRead: 0, cacheWrite: 0 }),
  ]);
  // cacheRead 80 / prompt (20+80+0+0) = 80.0%
  assert.match(notice.text, /Cache hit 80\.0%/);
  assert.match(notice.text, /^TPS \d+\.\d tok\/s\./);
});

test("no UI means no notice", () => {
  assert.deepEqual(runTurn([assistant(USAGE)], { hasUI: false }), []);
});

test("a turn with no output tokens stays silent", () => {
  assert.deepEqual(runTurn([assistant({ input: 20, output: 0, cacheRead: 0, cacheWrite: 0 })]), []);
});

test("every reader of timing.processStartedAt sees one value, not a fresh sample", () => {
  // Date.now() - performance.now() 를 부를 때마다 재면 ±1ms 흔들려 같은 프로세스인데도
  // 동등 비교가 산발적으로 깨진다. 모듈 상수로 한 번만 재야 한다.
  assert.equal(processStartedAt(), SHARED_PROCESS_STARTED_AT);
  assert.ok(Number.isInteger(SHARED_PROCESS_STARTED_AT));
  const sampled = Math.floor(Date.now() - performance.now());
  assert.ok(Math.abs(sampled - SHARED_PROCESS_STARTED_AT) <= 50);
});

test("the notice never prints think 0ms", () => {
  assert.equal(formatNoticeLatency({ waitMs: 900, thinkMs: 0 }), "delay 900ms");
  assert.equal(formatNoticeLatency({ waitMs: 1_200, thinkMs: 4_000 }), "delay 1.2s, think 4.0s");
  assert.equal(formatNoticeLatency(null), "");
});

test("the owned tps shim points at our module and never carries senpi's banner", () => {
  const agentDir = mkdtempSync(join(tmpdir(), "rubato-ext-"));
  const written = ensureAgentExtensions(agentDir);
  const target = join(agentDir, "extensions", "tps.js");
  assert.deepEqual(written, [target]);
  const content = readFileSync(target, "utf8");
  assert.ok(content.startsWith(RUBATO_EXTENSION_BANNER));
  assert.doesNotMatch(content, /^\/\/ Generated by/);
  assert.ok(content.includes(pathToFileURL(OWNED_AGENT_EXTENSIONS["tps.js"]).href));
  // 내용이 이미 맞으면 다시 쓰지 않는다 (senpi config-reload 워처를 흔들지 않으려고).
  assert.deepEqual(ensureAgentExtensions(agentDir), []);
});

test("a senpi-generated shim in the way is replaced by ours", () => {
  const agentDir = mkdtempSync(join(tmpdir(), "rubato-ext-"));
  mkdirSync(join(agentDir, "extensions"), { recursive: true });
  const target = join(agentDir, "extensions", "tps.js");
  writeFileSync(target, "// Generated by senpi. Delete this file to stop loading the default global extension.\nexport { default } from \"file:///nowhere.js\";\n");
  ensureAgentExtensions(agentDir);
  assert.equal(readFileSync(target, "utf8"), agentExtensionShim(OWNED_AGENT_EXTENSIONS["tps.js"]));
});

test("the shim loads and installs as a real extension", async () => {
  const agentDir = mkdtempSync(join(tmpdir(), "rubato-ext-"));
  ensureAgentExtensions(agentDir);
  const mod = await import(pathToFileURL(join(agentDir, "extensions", "tps.js")).href);
  const seen = [];
  mod.default({ on: (name) => seen.push(name) });
  assert.deepEqual(seen, ["agent_start", "message_start", "message_end", "agent_end"]);
});
